# Generated by Django 4.0.1 on 2022-01-21 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_youtube_channels_remove_facebook_post_post_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_content',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='youtube_channels',
            name='last_time_parsed',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 17, 42, 59, 763481)),
        ),
    ]
