# Generated by Django 4.0.1 on 2022-02-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_youtube_video_downloaded_captions_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
