# Generated by Django 4.0.1 on 2022-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_alter_youtube_channels_last_time_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_channels',
            name='last_time_parsed',
            field=models.DateTimeField(null=True),
        ),
    ]
