# Generated by Django 4.0.1 on 2022-01-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_alter_youtube_channels_last_time_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_post',
            name='social_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='instagram_post',
            name='social_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='twitter_post',
            name='social_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='youtube_post',
            name='social_id',
            field=models.TextField(default=''),
        ),
    ]
