# Generated by Django 4.0.1 on 2022-01-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_facebook_post_social_id_instagram_post_social_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_post',
            name='post_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts')], null=True),
        ),
        migrations.AlterField(
            model_name='youtube_post',
            name='caption',
            field=models.TextField(default='\n\nPrueba las herramientas que todo inversor inteligente necesita: https://inversionesyfinanzas.xyz\n\nVisita nuestras redes sociales:\nFacebook: https://www.facebook.com/InversionesyFinanzas/\nInstagram: https://www.instagram.com/inversiones.finanzas/\nTikTok: https://www.tiktok.com/@inversionesyfinanzas?\nTwitter : https://twitter.com/InvFinz\nLinkedIn : https://www.linkedin.com/company/inversiones-finanzas\n\nEn este canal de INVERSIONES & FINANZAS, aprende cómo realizar un BUEN ANÁLISIS de las EMPRESAS. Descubre dónde invertir y de qué forma ENCONTRAR BUENAS OPORTUNIDADES de INVERSIÓN.\n\nAPRENDE como invertir en la bolsa de valores.🥇 DESCUBRE las mejores ESTRATEGIAS que existen para INVERTIR y los pasos que deberías seguir para INVERTIR en la BOLSA mexicana de VALORES. ¿Quieres CONOCER la forma de INVERTIR de los INVERSORES más célebres de forma clara y FÁCIL? ADÉNTRATE en el ASOMBROSO mundo de las INVERSIONES. Si lo  que buscas es aprender a : \ninvertir en la bolsa de valores\ninvertir sin dinero\ninvertir con poco dinero\ninvertir siendo joven\nmultiplicar tu dinero\nanalizar una empresa\n'),
        ),
        migrations.AlterField(
            model_name='youtube_video_downloaded',
            name='url',
            field=models.TextField(default='', unique=True),
        ),
    ]
