# Generated by Django 4.0.1 on 2022-02-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_facebookpostrecord_instagrampostrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpostrecord',
            old_name='title',
            new_name='default_title',
        ),
        migrations.RenameField(
            model_name='instagrampostrecord',
            old_name='title',
            new_name='default_title',
        ),
        migrations.RenameField(
            model_name='twitterpostrecord',
            old_name='title',
            new_name='default_title',
        ),
        migrations.RenameField(
            model_name='youtubepostrecord',
            old_name='title',
            new_name='default_title',
        ),
    ]
