# Generated by Django 4.0.1 on 2022-02-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0013_alter_youtubevideodowloaded_content_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcontent',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
    ]
