# Generated by Django 4.0.1 on 2022-01-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEFAULT_TITLES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='EMOJIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FOLDERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='HASHTAGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('is_trending', models.BooleanField(default=False)),
                ('for_fb', models.BooleanField(default=False)),
                ('for_ig', models.BooleanField(default=False)),
                ('for_tw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LOCAL_CONTENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.UUIDField(null=True, unique=True)),
                ('main_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.folders')),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_local', models.BooleanField(default=True)),
                ('post_type', models.IntegerField(blank=True, choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost')], null=True)),
                ('is_original', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(default='')),
                ('content_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.local_content')),
                ('emojis', models.ManyToManyField(blank=True, to='modelos.EMOJIS')),
                ('hashtags', models.ManyToManyField(blank=True, to='modelos.HASHTAGS')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.default_titles')),
            ],
        ),
        migrations.CreateModel(
            name='YOUTUBE_POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.post')),
            ],
        ),
        migrations.CreateModel(
            name='YOUTUBE_VIDEO_DOWNLOADED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('old_title', models.TextField(default='')),
                ('new_title', models.TextField(default='')),
                ('original_channel', models.TextField(default='')),
                ('downloaded', models.BooleanField(default=False)),
                ('has_caption', models.BooleanField(default=False)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('post_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.youtube_post')),
            ],
        ),
        migrations.CreateModel(
            name='TWITTER_POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.post')),
            ],
        ),
        migrations.CreateModel(
            name='INSTAGRAM_POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.post')),
            ],
        ),
        migrations.CreateModel(
            name='FACEBOOK_POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.post')),
            ],
        ),
    ]
