# Generated by Django 4.0.1 on 2022-01-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_youtube_channels_last_time_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_post',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.default_titles'),
        ),
        migrations.AlterField(
            model_name='youtube_post',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
