# Generated by Django 4.0.1 on 2022-02-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_local_content_is_img_local_content_is_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_content',
            name='original_local',
            field=models.UUIDField(null=True),
        ),
    ]
