# Generated by Django 4.0.1 on 2022-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_local_content_original_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_content',
            name='error_msg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='local_content',
            name='has_consistent_error',
            field=models.BooleanField(default=False),
        ),
    ]
